classOrder = [
    "World",
    "SystemDefinition",
    "ComponentDefinition",
]

apiCategories = ["signal"]

title = "Stitch"
gitRepoUrl = "https://github.com/sayhisam1/Stitch"
gitSourceBranch = "master"
changelog = true

[home]
enabled = true
includeReadme = false

[docusaurus]
favicon = "/logo.png"
organizationName = "sayhisam1"
projectName = "Stitch"
url = "https://sayhisam1.github.io"
baseUrl = "/Stitch/"