classOrder = [
    "World",
    "SystemDefinition",
    "ComponentDefinition",
]

title = "Stitch"
gitRepoUrl = "https://github.com/sayhisam1/Stitch"

[home]
enabled = true
includeReadme = false

[docusaurus]
favicon = "/logo.png"
