local EntityManager = require(script.Parent.EntityManager)
local Observer = require(script.Parent.Observer)

return function()
	local entityManager
	local testInstance
	local testComponent = {
		name = "test",
	}
	beforeEach(function()
		entityManager = EntityManager.new("test")
		entityManager:registerComponent(testComponent)
		testInstance = Instance.new("Part")
	end)

	afterEach(function()
		entityManager:destroy()
		testInstance:Destroy()
	end)

	describe("Observer.new", function()
		it("should create a new observer", function()
			local observer = Observer.new()
			expect(observer).to.be.ok()
		end)
	end)
	describe("Observer:get", function()
		it("should update when a new entity is added", function()
			local observer = Observer.new(entityManager:getEntityAddedSignal(testComponent))
			entityManager:addComponent(testComponent, testInstance)
			expect(next(observer:get())).to.equal(testInstance)
		end)
		it("should update when an entity component is set", function()
			local observer = Observer.new(entityManager:getEntityChangedSignal(testComponent))
			entityManager:addComponent(testComponent, testInstance)
			expect(next(observer:get())).to.never.be.ok()
			entityManager:setComponent(testComponent, testInstance, {})
			expect(next(observer:get())).to.equal(testInstance)
		end)
		it("should update when an entity component is updated", function()
			local observer = Observer.new(entityManager:getEntityChangedSignal(testComponent))
			entityManager:addComponent(testComponent, testInstance)
			expect(next(observer:get())).to.never.be.ok()
			entityManager:updateComponent(testComponent, testInstance, {})
			expect(next(observer:get())).to.equal(testInstance)
		end)
		it("should update when an entity component is removed", function()
			local observer = Observer.new(entityManager:getEntityRemovedSignal(testComponent))
			entityManager:addComponent(testComponent, testInstance)
			expect(next(observer:get())).to.never.be.ok()
			entityManager:removeComponent(testComponent, testInstance)
			expect(next(observer:get())).to.equal(testInstance)
		end)
		it("should update when multiple events occur", function()
			local observer = Observer.new(
				entityManager:getEntityChangedSignal(testComponent),
				entityManager:getEntityAddedSignal(testComponent),
				entityManager:getEntityRemovedSignal(testComponent)
			)
			entityManager:addComponent(testComponent, testInstance)
			expect(next(observer:get())).to.equal(testInstance)
			observer:clear()
			expect(next(observer:get())).to.never.be.ok()

			entityManager:setComponent(testComponent, testInstance, {})
			expect(next(observer:get())).to.equal(testInstance)
			observer:clear()
			expect(next(observer:get())).to.never.be.ok()

			entityManager:removeComponent(testComponent, testInstance)
			expect(next(observer:get())).to.equal(testInstance)
			observer:clear()
			expect(next(observer:get())).to.never.be.ok()
		end)
	end)
	describe("Observer:mark", function()
		it("should mark", function()
			local observer = Observer.new(entityManager:getEntityAddedSignal(testComponent))
			entityManager:addComponent(testComponent, testInstance)
			local testEntity = {}
			local testData = {}
			observer:mark(testEntity, testData)
			expect(observer:get()[testEntity]).to.equal(testData)
		end)
		it("should error on invalid data", function()
			local observer = Observer.new(entityManager:getEntityAddedSignal(testComponent))
			entityManager:addComponent(testComponent, testInstance)
			local testEntity = {}
			expect(function()
				observer:mark(testEntity)
			end).to.throw()
		end)
	end)
end
