name: build-stitch-docs

on:
  push:
    branches:
      - master

jobs:  
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install moonwave
        run: npm install moonwave

      - name: Build docs
        run: |
          npx moonwave build

      - name: Force push to gh-pages
        run: |
          rm -rf .git
          cd build
          git init .
          git add -f *
          git -c user.name='gh-actions' -c user.email='gh-actions' commit -m "Docs update"
          git push --force https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/sayhisam1/Stitch HEAD:gh-pages
