name: build-stitch-docs

on:
  push:
    branches:
      - master

jobs:  
  publish-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install moonwave
        run: npm install moonwave

      - name: Build docs
        run: |
          npx moonwave build
          cd build

      - name: Force push to gh-pages
        uses: dfm/force-push-branch-action@v1
        with:
          path: "*"
          target-branch: "gh-pages"
          github-token: ${{secrets.GITHUB_TOKEN}}
          commit-message: "Automatic docs built with Github Actions"
