name: CI

on: [push]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: download roblox install script
      uses: OrbitalOwen/roblox-win-installer-action@1.1
      with:
        cookie: ${{ secrets.ROBLOSECURITY }}
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: install foreman
      uses: rojo-rbx/setup-foreman@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: install foreman packages (rojo, run-in-roblox)
      run: foreman install

    - name: run rojo build
      run: rojo build develop.project.json --output tests.rbxlx
    
    - name: listfiles
      run: tree

    - name: run tests
      run: run-in-roblox --place tests.rbxlx --script test/ci_runtest.lua
